name: Integration Test
on: [push]
jobs:
  build:
    runs-on: zhengt-wsl
    outputs:
      buildOutput: ${{ steps.selftest.outputs.myOutput }}
    steps:
      - uses: actions/checkout@master
      - name: Self test
        id: selftest

        # Put your action repo here
        uses: zhengt/python-actions@master

      - name: Check outputs
        run: |
          test "${{ steps.selftest.outputs.myOutput }}" == "Hello world"
  deploy:
    needs: [build]
    runs-on: zhengt-wsl
    steps:
      - name: Use output from previous job
        run: echo "${{ needs.build.outputs.buildOutput }}"

  job1:
    runs-on: zhengt-wsl
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
    - id: step1
      run: echo "::set-output name=test::hello"
    - id: step2
      run: echo "::set-output name=test::world"
  job2:
    runs-on: zhengt-wsl
    needs: job1
    steps:
    - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}
